spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: sdpark98@

    properties:
      hibernate:
        format_sql: true

logging:
  slack:
    webhook-uri: https://hooks.slack.com/services/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
    config: classpath:logback-spring.xml
jwt:
  secret: adwiuhdfksedihiciueksgruczhieushkfkzeiuzhfkisuhseiufhsiezufhsiuehziseuhfwaudhawuikhiuawh

oauth:

server:
  servlet:
    context-path: /api

