spring:
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - https://www.googleapis.com/auth/youtube.readonly
              - https://www.googleapis.com/auth/yt-analytics.readonly
              - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
          meta:
            client-id: ${META_CLIENT_ID}
            client-secret: ${META_CLIENT_SECRET}
            scope:
              - pages_show_list
              - ads_read
              - instagram_basic
              - instagram_manage_insights
              - pages_read_engagement
            redirect-uri: ${META_REDIRECT_URI}
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
          meta:
            #https://www.facebook.com/v22.0/dialog/oauth?client_id=626129706854931&redirect_uri=https://app-spark.shop/oauth/meta&scope=pages_show_list,ads_read,instagram_basic,instagram_manage_insights,pages_read_engagement&response_type=code 참고
            authorization-uri: https://www.facebook.com/v22.0/dialog/oauth
            token-uri: https://graph.facebook.com/v22.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id
    properties:
      hibernate:
        format_sql: true
oauth:

server:
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    tagsSorter: alpha
    oauth2-redirect-url: http://localhost:8080/oauth/google
    enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.security: DEBUG
  slack:
    webhook-uri: ${SLACK_WEBHOOK_URI}
  config: classpath:logback-spring.xml
openai:
  api-key: ${OPENAI_API_KEY}

pinecone:
  api-key: ${PINECONE_API_KEY}
  host: ${PINECONE_HOST}
  index-name: ${PINECONE_INDEX_NAME}

